package autonomy

import "time"

// CorrectionOption describes one action candidate generated by planner.
type CorrectionOption struct {
	Action               string  `json:"action"`
	EstimatedRisk        float64 `json:"estimated_risk"`
	EstimatedMissionGain float64 `json:"estimated_mission_gain"`
	EstimatedCost        float64 `json:"estimated_cost"`
}

// CorrectionDecision is a policy-scored planner output.
type CorrectionDecision struct {
	SelectedAction string    `json:"selected_action"`
	Score          float64   `json:"score"`
	EvaluatedAt    time.Time `json:"evaluated_at"`
	RejectedUnsafe bool      `json:"rejected_unsafe"`
}

// PlannerPolicy constrains autonomous decisions.
type PlannerPolicy struct {
	MaxAcceptedRisk float64
	MinMissionGain  float64
}

// SelectBestCorrection chooses the highest utility safe action.
func SelectBestCorrection(options []CorrectionOption, policy PlannerPolicy) CorrectionDecision {
	best := CorrectionDecision{SelectedAction: "hold_position", Score: -1, EvaluatedAt: time.Now().UTC(), RejectedUnsafe: true}
	for _, opt := range options {
		risk := ClampUnitInterval(opt.EstimatedRisk)
		gain := ClampUnitInterval(opt.EstimatedMissionGain)
		cost := ClampUnitInterval(opt.EstimatedCost)
		if risk > ClampUnitInterval(policy.MaxAcceptedRisk) {
			continue
		}
		if gain < ClampUnitInterval(policy.MinMissionGain) {
			continue
		}
		score := (gain * 0.6) + ((1 - risk) * 0.3) + ((1 - cost) * 0.1)
		if score > best.Score {
			best = CorrectionDecision{
				SelectedAction: opt.Action,
				Score:          score,
				EvaluatedAt:    time.Now().UTC(),
				RejectedUnsafe: false,
			}
		}
	}
	return best
}
