name: Lint Code Base

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    name: Lint and Validate
    if: github.event_name != 'pull_request' || github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          # Full git history is needed for linter to check only changed files
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@61abc07d755095a68f4987d1c2c3d1d64408f1f9
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: false
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
          SAVE_SUPER_LINTER_SUMMARY: true
          # Tailored to your specific repo stack
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_TERRAFORM: true
          VALIDATE_BASH: true
          VALIDATE_DOCKERFILE: true
